"""Staging a complete, buildable copy of the course source into Output/.

The point of copying the whole tree rather than just the JSON is that the
result is something you can run ``grunt build`` inside directly - theme, less,
components and all - without touching the authored source.
"""

from __future__ import annotations

import shutil
from dataclasses import dataclass
from pathlib import Path

#: Directories never worth copying: reinstallable, huge, or VCS metadata.
DEFAULT_EXCLUDES = {
    "node_modules",
    ".git",
    "__pycache__",
    ".cache",
    ".tmp",
    # `build/` is grunt's compiled output. Copying it would carry the *old*
    # course JSON into a folder that is supposed to represent the new one, so
    # it is left out and regenerated by `grunt build`. Pass --include-build to
    # override.
    "build",
}


@dataclass
class CopyStats:
    files: int = 0
    bytes: int = 0
    skipped_dirs: int = 0

    @property
    def megabytes(self) -> float:
        return round(self.bytes / (1024 * 1024), 1)


def _force_remove(func, path, _exc):
    """rmtree handler: clear the read-only bit Windows sets on some assets."""
    import os
    import stat

    try:
        os.chmod(path, stat.S_IWRITE)
        func(path)
    except OSError:
        pass


#: Kept when refreshing a staged course: expensive to recreate and not ours to
#: manage. Preserving node_modules is what makes `npm install` a one-off.
PRESERVE_ON_REFRESH = {"node_modules", ".git", "build"}


def clear_directory(target: Path, preserve: set[str] | None = None) -> None:
    """Empty ``target`` without deleting it, keeping ``preserve`` entries.

    Explorer or an editor frequently holds a handle on the output folder
    itself, which makes removing the root fail on Windows even though its
    contents delete fine.
    """
    preserve = preserve or set()
    for child in target.iterdir():
        if child.name in preserve:
            continue
        if child.is_dir() and not child.is_symlink():
            shutil.rmtree(child, onexc=_force_remove)
        else:
            try:
                child.unlink()
            except OSError:
                pass


def clear_media(assets: Path, keep: set[str]) -> int:
    """Empty the staged theme's media folders, keeping ``keep``.

    A staged course starts as a copy of the base course, media and all. Those
    files belong to the base, not to the course being built, so they are
    cleared before this course's own figures, video and PDF are written -
    otherwise every course would ship the base's sample media. ``keep`` holds
    the player art, which the theme's CSS refers to by name.
    """
    removed = 0
    for folder in sorted(p for p in assets.iterdir() if p.is_dir()):
        if folder.name in keep:
            continue
        for child in sorted(folder.rglob("*"), key=lambda c: -len(c.parts)):
            if child.is_dir():
                try:
                    child.rmdir()  # only if the files inside it are gone
                except OSError:
                    pass
                continue
            try:
                child.unlink()
                removed += 1
            except OSError:
                pass
    return removed


def stage_course(
    source: Path,
    dest: Path,
    excludes: set[str] | None = None,
    *,
    clean: bool = True,
) -> CopyStats:
    """Copy ``source`` to ``dest``, skipping ``excludes`` by directory name."""
    excludes = DEFAULT_EXCLUDES if excludes is None else excludes
    stats = CopyStats()

    # Only keep what this run is not going to copy in anyway - so
    # --include-build refreshes build/ rather than merging into a stale one.
    preserve = PRESERVE_ON_REFRESH & excludes

    if clean and dest.exists():
        clear_directory(dest, preserve)
    dest.mkdir(parents=True, exist_ok=True)

    def ignore(directory: str, names: list[str]) -> set[str]:
        skipped = {n for n in names if n in excludes}
        stats.skipped_dirs += len(skipped)
        return skipped

    shutil.copytree(source, dest, ignore=ignore, dirs_exist_ok=True)

    # Count only what was staged - a preserved node_modules would dwarf it.
    for child in dest.iterdir():
        if child.name in preserve:
            continue
        for path in [child, *child.rglob("*")] if child.is_dir() else [child]:
            if path.is_file():
                stats.files += 1
                stats.bytes += path.stat().st_size

    return stats


def backup(target: Path, backup_root: Path, label: str) -> Path | None:
    """Snapshot ``target`` under ``backup_root`` before it is overwritten."""
    if not target.exists():
        return None
    destination = backup_root / label / target.name
    destination.parent.mkdir(parents=True, exist_ok=True)
    if target.is_dir():
        shutil.copytree(target, destination, dirs_exist_ok=True)
    else:
        shutil.copy2(target, destination)
    return destination
